Add openfaas ingress operator chart
openfaas/faas-netes pull request #666
Opened 2020-06-28 14:26 UTC by viveksyngh

## Description

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2020-09-17 08:15 UTC, Waterdrips requested changes

2020-09-17 08:15 UTC, Waterdrips commented on chart/ingress-operator/templates/ingress-operator-dep.yaml
> +{{- if .Values.create }}
Don't we always want to create these things now it's in it's own chart? (few files with this in)

2020-09-17 08:15 UTC, Waterdrips commented on chart/ingress-operator/values.yaml
> +create: false
Won't we want to get rid of this value as this is explicitly True when installing this now

2020-11-03 21:35 UTC, alexellis commented
Didn't this happen @viveksyngh ?

2020-11-11 03:45 UTC, viveksyngh commented
I think this one was for migrating ingress operator to it's own helm chart.

2021-11-01 09:47 UTC, alexellis commented
We did this separately a while back so I'm closing the PR.

2021-11-01 09:47 UTC, closed without merging

2021-11-01 09:47 UTC, alexellis commented
/lock